ccflags-$(CONFIG_RK_HDMI_DEBUG) = -DDEBUG -DHDMI_DEBUG

obj-$(CONFIG_MHL_IT6811)       += it6811_mhl.o \
					hdmi_drv.o \
					ite_drv_mhl_tx.o \
					ite_drv_mhl_tx_edid.o \
					ite_hal_linux_gpio.o \
					ite_hal_linux_i2c.o \
					ite_hal_linux_init.o \
					ite_hal_linux_isr.o \
					ite_hal_linux_timer.o \
					ite_mhl_tx.o \
					ite_mhl_tx_rcp_table.o \
					ite_osal_linux_timer.o \
					ite_osdebug.o \
					it6811_mhl_hw.o 

